#
# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2023  Ammar Faizi <ammarfaizi2@gnuweeb.org>
#

DEP_DIRS += $(BASE_DEP_DIR)/src/teavpn2/ap/linux

include $(BASE_DIR)/src/teavpn2/ap/linux/net/Makefile
include $(BASE_DIR)/src/teavpn2/ap/linux/client/Makefile
include $(BASE_DIR)/src/teavpn2/ap/linux/server/Makefile

OBJ_CC += \
	$(BASE_DIR)/src/teavpn2/ap/linux/mutex.o
