#
# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2023  Ammar Faizi <ammarfaizi2@gnuweeb.org>
#

DEP_DIRS += $(BASE_DEP_DIR)/src/teavpn2/ap

ifeq ($(CONFIG_LINUX),y)
include $(BASE_DIR)/src/teavpn2/ap/linux/Makefile
endif
