#
# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2023  Ammar Faizi <ammarfaizi2@gnuweeb.org>
#

DEP_DIRS += $(BASE_DEP_DIR)/src/teavpn2/ap/linux/server

OBJ_CC += \
	$(BASE_DIR)/src/teavpn2/ap/linux/server/entry.o \
	$(BASE_DIR)/src/teavpn2/ap/linux/server/udp_epoll.o \
	$(BASE_DIR)/src/teavpn2/ap/linux/server/udp.o
